[workspace.package]
authors = ["Nova Labs <info@nova-labs.com>"]
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/helium/helium-wallet-rs"

[workspace]
members = [
    "helium-wallet",
    "helium-lib",
    "helium-mnemonic"
]
resolver = "2"

[workspace.dependencies]
sha2 = "0.10"
base64 = ">=0.21"
serde = "1"
serde_json = "1"
rust_decimal = { version = "1", features = ["serde-float"] }
helium-crypto = { version = "0.8" }
helium-proto = { git = "https://github.com/helium/proto", branch = "master" }
clap = { version = "4", features = ["derive"] }
