[package]
name = "helium-lib"
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
clap = ["dep:clap"]
mnemonic = ["helium-mnemonic"]

[dependencies]
hex = "0.4"
chrono = {version = "0", features = ["serde"]}
thiserror = "1"
pyth-sdk-solana = "0"
async-trait = "0"
anchor-client = {version = "0.29.0", features = ["async"] }
anchor-spl = { version = "0.29.0", features = ["mint", "token"] }
url = {version = "2", features = ["serde"]}
h3o = {version = "0", features = ["std", "serde"]}
helium-crypto = {workspace = true}
itertools = "0"
jsonrpc_client = {version = "0.7", features = ["reqwest"]}
futures = "*"
tracing = "0"
base64 = {workspace = true}
solana-sdk = "1.16"
bincode = "1.3.3"
reqwest = { version = "0", default-features = false, features = [
    "rustls-tls",
] }
helium-anchor-gen = {git = "https://github.com/helium/helium-anchor-gen.git"}
spl-associated-token-account = { version = "*", features = ["no-entrypoint"] }
solana-program = "*"
solana-transaction-status = "*"
serde = {workspace = true}
serde_json = {workspace = true}
serde_with = "2"
lazy_static = "1"
rust_decimal = {workspace = true}
helium-proto = {workspace= true}
angry-purple-tiger = "0"
sha2 = {workspace = true}
clap = {workspace = true, optional = true}
helium-mnemonic = { path = "../helium-mnemonic", optional = true }
